### ISSUE TITLE
大事不好啦！！！

### ISSUE THREAD

**Issue by AymaxLi** [hefengly/prepare-for-interview#1]
[这里](https://github.com/hefengly/prepare-for-interview/blob/master/Performance/js%20%E5%87%BD%E6%95%B0%E7%9A%84%E8%8A%82%E6%B5%81%E5%92%8C%E9%98%B2%E6%8A%96.md)的防抖为什么用 call 咧，而且 args 是不是有问题呢 ~

**Comment by hefengly** [comment]
改了～～哈哈哈，谢谢杰杰～
